import type { Rule } from "@/lib/types";

const ZINP = "Zakon o izboru narodnih poslanika";
const ZINP_URL = "https://www.rik.parlament.gov.rs/tekst/sr/61/zakoni.php";
const ZINP_TOK = { law: ZINP, article: "čl. 87–99 (opšti tok glasanja)", url: ZINP_URL };
const ZINP_89 = { law: ZINP, article: "čl. 89", url: ZINP_URL };
const ZINP_93 = { law: ZINP, article: "čl. 93", url: ZINP_URL };
const ZINP_96 = { law: ZINP, article: "čl. 96 · glasanje van biračkog mesta", url: ZINP_URL };
const ZINP_102 = { law: ZINP, article: "čl. 102 · utvrđivanje broja birača koji su glasali", url: ZINP_URL };
const ZINP_116 = { law: ZINP, article: "čl. 116 · poništavanje po službenoj dužnosti", url: ZINP_URL };
const KZ = "Krivični zakonik Republike Srbije";
const KZ_URL = "https://reg.pravno-informacioni-sistem.rs/api/viewdoc?doctype=reg&regactid=437844&uuid=f9f75050-d16f-484a-acad-4be0f1a5bcf5";

const SVI = ["narodni_poslanici", "predsednik", "lokalni"];

export const rules: Rule[] = [
  // ---------------- PRE OTVARANJA ----------------
  {
    id: "P01",
    slug: "nedostaje-izvod-birackog-spiska",
    naziv: "Nedostaje izvod iz biračkog spiska",
    kategorija: "pre_otvaranja",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Pre otvaranja nedostaje izvod iz biračkog spiska za to biračko mesto.",
    legalRule:
      "Ako pre otvaranja biračkog mesta nedostaje deo izbornog materijala bez kojeg glasanje ne može da se sprovede (izvod iz biračkog spiska, glasačka kutija ili kontrolni list), biračko mesto se ne otvara.",
    legalEffect: "Biračko mesto se ne otvara dok se nedostatak ne otkloni.",
    whatToCheck: [
      "Da li izvod uopšte postoji u materijalu koji je odbor preuzeo",
      "Da li je problem prijavljen nadležnoj izbornoj komisiji",
    ],
    controllerActions: [
      "Ne otvarati biračko mesto dok materijal nije kompletan",
      "Odmah obavestiti nadležnu izbornu komisiju",
      "Zabeležiti tačno vreme uočavanja nedostatka",
    ],
    voterActions: ["Sačekaj zvanično obaveštenje odbora, ne napuštaj red bez informacije"],
    observerActions: ["Zabeleži vreme i razlog kašnjenja otvaranja u sopstveni zapisnik"],
    evidenceChecklist: ["Vreme uočavanja", "Ko je obavešten", "Kada je materijal dopunjen"],
    doNotDo: ["Ne otvarati glasanje „privremeno“ dok se čeka materijal"],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["nedostaje-glasacka-kutija", "nedostaje-kontrolni-list-pre-otvaranja"],
    order: 1,
  },
  {
    id: "P02",
    slug: "nedostaje-glasacka-kutija",
    naziv: "Nedostaje glasačka kutija",
    kategorija: "pre_otvaranja",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Glasačka kutija nije deo preuzetog izbornog materijala.",
    legalRule:
      "Glasačka kutija je deo materijala bez kojeg se glasanje ne može sprovesti. Biračko mesto se ne otvara dok kutija ne stigne.",
    legalEffect: "Biračko mesto se ne otvara.",
    whatToCheck: ["Da li je kutija zamenjena ispravnom pre stvarnog otvaranja"],
    controllerActions: ["Ne otvarati mesto", "Prijaviti izbornoj komisiji odmah"],
    voterActions: [],
    observerActions: ["Zabeleži tačno vreme i tok rešavanja"],
    evidenceChecklist: ["Vreme", "Ko je kontaktiran", "Kada je kutija dopremljena"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["nedostaje-izvod-birackog-spiska"],
    order: 2,
  },
  {
    id: "P03",
    slug: "nedostaje-kontrolni-list-pre-otvaranja",
    naziv: "Nedostaje kontrolni list (pre otvaranja)",
    kategorija: "pre_otvaranja",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Kontrolni list nije zatečen u preuzetom izbornom materijalu.",
    legalRule:
      "Kontrolni list je obavezan deo materijala. Ako nedostaje, biračko mesto se ne otvara dok se pitanje ne reši sa izbornom komisijom.",
    legalEffect: "Biračko mesto se ne otvara.",
    whatToCheck: [],
    controllerActions: ["Ne otvarati mesto", "Odmah kontaktirati izbornu komisiju"],
    voterActions: [],
    observerActions: ["Zabeleži vreme i razlog"],
    evidenceChecklist: ["Vreme", "Komunikacija sa komisijom"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["kontrolni-list-nije-popunjen"],
    order: 3,
  },
  {
    id: "P04",
    slug: "manji-broj-listica-nije-razlog-za-neotvaranje",
    naziv: "Manji broj listića od broja birača nije razlog da se mesto ne otvori",
    kategorija: "pre_otvaranja",
    severity: "info",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary:
      "Ako je broj primljenih glasačkih listića manji od broja upisanih birača, to samo po sebi nije razlog da se biračko mesto ne otvori.",
    legalRule:
      "Zakon posebno predviđa da se u ovom slučaju biračko mesto ipak otvara, za razliku od nedostatka izvoda, kutije ili kontrolnog lista.",
    legalEffect: "Glasanje počinje po planu; dopuna listića se rešava u hodu preko izborne komisije.",
    whatToCheck: ["Da li je odbor prijavio nedostatak listića komisiji radi blagovremene dopune"],
    controllerActions: ["Otvoriti biračko mesto u zakazano vreme", "Zatražiti dopunu listića"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    mythCheck: {
      claim: "Ako nema dovoljno listića za sve upisane birače, biračko mesto se ne otvara.",
      verdict: "mit",
      explanation:
        "Zakon ovaj slučaj tretira drugačije od nedostatka izvoda, kutije ili kontrolnog lista: mesto se otvara, a listići se dopunjuju.",
    },
    order: 4,
  },
  {
    id: "P05",
    slug: "kutija-nije-pokazana-prazna",
    naziv: "Kutija nije pokazana prazna prvom biraču",
    kategorija: "pre_otvaranja",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Pred prvim biračem nije utvrđeno da je glasačka kutija prazna i ispravna.",
    legalRule:
      "Pre početka glasanja, pred prvim biračem se utvrđuje da je glasačka kutija prazna i ispravna, nakon čega se ubacuje kontrolni list i kutija se pečati.",
    legalEffect:
      "Ako je propust primećen pre pečaćenja, procedura se može sprovesti ispravno; ako je glasanje već počelo, činjenicu treba uneti u zapisnik i odmah obavestiti nadležnu izbornu komisiju.",
    whatToCheck: ["Da li je prvi birač zaista bio prisutan i video prazan prostor kutije"],
    controllerActions: [
      "Ako kutija još nije zapečaćena, sprovesti proveru pred prvim biračem i popuniti kontrolni list",
      "Ako je glasanje već počelo, ne pokušavati naknadnu rekonstrukciju; uneti činjenicu u zapisnik i obavestiti komisiju",
    ],
    voterActions: ["Ako si prvi birač i ovo se preskoči, zatraži da se procedura sprovede pre nego što glasaš"],
    observerActions: ["Zabeleži da li je provera sprovedena pred svedocima"],
    evidenceChecklist: ["Vreme otvaranja", "Ko je prvi birač", "Da li je provera sprovedena"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["kontrolni-list-nije-popunjen"],
    order: 5,
  },
  {
    id: "P06",
    slug: "kontrolni-list-nije-popunjen",
    naziv: "Kontrolni list nije popunjen",
    kategorija: "pre_otvaranja",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Kontrolni list koji treba da bude ubačen u kutiju pre pečaćenja nije uopšte popunjen.",
    legalRule:
      "Kontrolni list se popunjava, potpisuje ga prvi birač i najmanje jedan član biračkog odbora, ubacuje se u kutiju, pa se kutija pečati.",
    legalEffect:
      "Ako se pri otvaranju kutije utvrdi da kontrolni list nije popunjen, to je jedan od zakonom izričito propisanih razloga za poništavanje glasanja na tom biračkom mestu po službenoj dužnosti.",
    whatToCheck: ["Da li kontrolni list uopšte postoji u kutiji pri otvaranju"],
    controllerActions: [
      "Pre pečaćenja popuniti i potpisati kontrolni list prema propisanoj proceduri",
      "Ako je kutija već zapečaćena, ne dopisivati podatke naknadno; uneti činjenicu u zapisnik i obavestiti komisiju",
    ],
    voterActions: [],
    observerActions: ["Zabeleži da li je kontrolni list vidljivo popunjen pre pečaćenja"],
    evidenceChecklist: ["Da li je kontrolni list popunjen", "Ko je prisustvovao"],
    doNotDo: [],
    lawReferences: [ZINP_116],
    sourceUrls: [],
    relatedSlugs: [
      "kontrolni-list-bez-potpisa-prvog-biraca",
      "kontrolni-list-bez-potpisa-clana-odbora",
      "kontrolni-list-nije-ubacen-u-kutiju",
    ],
    isAutomaticAnnulment: true,
    order: 6,
  },
  {
    id: "P07",
    slug: "kontrolni-list-bez-potpisa-prvog-biraca",
    naziv: "Kontrolni list nije potpisao prvi birač",
    kategorija: "pre_otvaranja",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Kontrolni list postoji, ali ga prvi birač nije potpisao.",
    legalRule: "Kontrolni list mora potpisati prvi birač i najmanje jedan član biračkog odbora.",
    legalEffect: "Zakonski osnov za poništavanje glasanja na biračkom mestu po službenoj dužnosti.",
    whatToCheck: ["Da li potpis prvog birača zaista nedostaje ili je samo nečitak"],
    controllerActions: [
      "Pre pečaćenja obezbediti potpis prvog birača prema propisanoj proceduri",
      "Ako je kutija već zapečaćena, ne dopisivati potpis naknadno; uneti primedbu u zapisnik",
    ],
    voterActions: [],
    observerActions: ["Proveri vidljivost potpisa pri otvaranju kutije nakon glasanja"],
    evidenceChecklist: ["Fotografija/opis stanja kontrolnog lista pri otvaranju kutije"],
    doNotDo: [],
    lawReferences: [ZINP_116],
    sourceUrls: [],
    relatedSlugs: ["kontrolni-list-nije-popunjen"],
    isAutomaticAnnulment: true,
    order: 7,
  },
  {
    id: "P08",
    slug: "kontrolni-list-bez-potpisa-clana-odbora",
    naziv: "Kontrolni list nije potpisao nijedan član odbora",
    kategorija: "pre_otvaranja",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Kontrolni list nema potpis nijednog člana biračkog odbora.",
    legalRule: "Kontrolni list mora potpisati i najmanje jedan član biračkog odbora, uz prvog birača.",
    legalEffect: "Zakonski osnov za poništavanje glasanja na biračkom mestu po službenoj dužnosti.",
    whatToCheck: [],
    controllerActions: [
      "Pre pečaćenja obezbediti potpis najmanje jednog člana odbora prema propisanoj proceduri",
      "Ako je kutija već zapečaćena, ne dopisivati potpis naknadno; uneti primedbu u zapisnik",
    ],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_116],
    sourceUrls: [],
    relatedSlugs: ["kontrolni-list-nije-popunjen"],
    isAutomaticAnnulment: true,
    order: 8,
  },
  {
    id: "P09",
    slug: "kontrolni-list-nije-ubacen-u-kutiju",
    naziv: "Kontrolni list nije ubačen u kutiju",
    kategorija: "pre_otvaranja",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["brojanje"],
    summary: "Pri otvaranju kutije posle glasanja, kontrolni list se u njoj ne nalazi.",
    legalRule: "Kontrolni list se ubacuje u kutiju pre pečaćenja, pred prvim biračem.",
    legalEffect:
      "Ako kontrolnog lista nema pri otvaranju kutije, to je zakonski osnov za poništavanje glasanja na biračkom mestu po službenoj dužnosti.",
    whatToCheck: ["Da li je moguće da je list zaostao među listićima pre konačnog zaključka"],
    controllerActions: ["Detaljno pretražiti sadržaj kutije pre donošenja zaključka", "Uneti nalaz u zapisnik"],
    voterActions: [],
    observerActions: ["Prati pretragu kutije pri brojanju"],
    evidenceChecklist: ["Da li je kontrolni list pronađen", "Ko je pretraživao kutiju"],
    doNotDo: [],
    lawReferences: [ZINP_116],
    sourceUrls: [],
    relatedSlugs: ["kontrolni-list-nije-popunjen", "vise-listica-u-kutiji-nego-biraca"],
    isAutomaticAnnulment: true,
    order: 9,
  },
  {
    id: "P10",
    slug: "kutija-nije-zapecacena",
    naziv: "Kutija nije propisno zapečaćena",
    kategorija: "pre_otvaranja",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Nakon ubacivanja kontrolnog lista, kutija nije propisno zapečaćena.",
    legalRule: "Nakon ubacivanja kontrolnog lista, glasačka kutija se pečati pre početka glasanja.",
    legalEffect: "Teška proceduralna nepravilnost, dovodi u pitanje ispravnost kutije tokom celog dana.",
    whatToCheck: ["Stanje pečata tokom dana i pri zatvaranju"],
    controllerActions: ["Zaustaviti glasanje dok se kutija propisno ne zapečati", "Uneti primedbu u zapisnik"],
    voterActions: [],
    observerActions: ["Prati stanje pečata tokom dana"],
    evidenceChecklist: ["Fotografija/opis pečata", "Vreme pečaćenja"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 10,
  },
  {
    id: "P11",
    slug: "paravani-ne-obezbedjuju-tajnost",
    naziv: "Paravani ne obezbeđuju tajnost glasanja",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Paravani su postavljeni tako da se sa strane ili iz reda može videti kako birač popunjava listić.",
    legalRule:
      "Paravani moraju biti raspoređeni tako da ni drugi birači, ni članovi odbora, ni posmatrači ne mogu videti kako birač popunjava listić.",
    legalEffect: "Povreda garancije tajnosti glasanja za sve birače koji glasaju dok stanje traje.",
    whatToCheck: ["Ugao gledanja od stola odbora, ulaza i reda čekanja"],
    controllerActions: ["Zahtevati premeštanje paravana pre nastavka glasanja"],
    voterActions: ["Ukazati odboru ako primetiš da te neko može videti dok glasaš"],
    observerActions: ["Proveri raspored paravana na početku obilaska"],
    evidenceChecklist: ["Opis/skica rasporeda prostorije"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 11,
  },
  {
    id: "P12",
    slug: "propaganda-na-birackom-mestu",
    naziv: "Stranački simboli ili propagandni materijal u prostoru",
    kategorija: "pre_otvaranja",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["pre_otvaranja"],
    summary: "Na biračkom mestu ili neposredno ispred njega nalazi se stranački simbol ili izborni propagandni materijal.",
    legalRule:
      "Isticanje stranačkih simbola i izbornog propagandnog materijala na biračkom mestu ili neposredno ispred njega zakon navodi kao narušavanje reda.",
    legalEffect: "Narušavanje reda na biračkom mestu koje birački odbor treba odmah da otkloni.",
    whatToCheck: ["Da li se materijal nalazi unutar ili neposredno ispred mesta"],
    controllerActions: ["Zahtevati uklanjanje materijala", "Uneti primedbu u zapisnik ako se ne ukloni"],
    voterActions: [],
    observerActions: ["Fotografisati materijal samo van biračkog mesta i bez ometanja glasanja"],
    evidenceChecklist: ["Lokacija", "Vreme", "Opis materijala"],
    doNotDo: ["Ne fotografisati unutrašnjost biračkog mesta radi ovoga"],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 12,
  },

  // ---------------- IDENTITET I BIRAČKI SPISAK ----------------
  {
    id: "I01",
    slug: "preskocena-uv-provera",
    naziv: "Preskočena UV provera",
    kategorija: "identitet_spisak",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birač dobija glasački listić bez prethodne provere UV lampom.",
    legalRule:
      "Redosled provere pre izdavanja listića je: UV lampa, utvrđivanje identiteta, provera u izvodu biračkog spiska, potpis, UV sprej, pa tek onda jedan glasački listić.",
    legalEffect: "Proceduralna nepravilnost koja slabi zaštitu od višestrukog glasanja.",
    whatToCheck: ["Da li je UV lampa uopšte prisutna i ispravna na biračkom mestu"],
    controllerActions: ["Zahtevati da se procedura odmah počne da sprovodi ispravno", "Uneti primedbu u zapisnik"],
    voterActions: [],
    observerActions: ["Prati da li se korak dosledno primenjuje kod svakog birača"],
    evidenceChecklist: ["Vreme", "Broj birača kod kojih je korak preskočen"],
    doNotDo: [],
    lawReferences: [ZINP_93],
    sourceUrls: [],
    relatedSlugs: ["preskocen-uv-sprej"],
    order: 13,
  },
  {
    id: "I02",
    slug: "uv-trag-clan-biracke-komisije-izuzetak",
    naziv: "UV trag kod birača koji je član biračkog odbora",
    kategorija: "identitet_spisak",
    severity: "proveri",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary:
      "UV lampa pokazuje trag kod birača, ali on tvrdi da je član drugog biračkog odbora i ima odgovarajuće rešenje.",
    legalRule:
      "Zakon predviđa poseban izuzetak za birača koji dokaže da je član biračkog odbora: takva osoba može ponovo glasati na drugom mestu uz odgovarajuće rešenje/potvrdu, jer je UV trag posledica ranijeg obavljanja dužnosti, a ne dvostrukog glasanja.",
    legalEffect: "Ako je izuzetak dokazan, glasanje je dozvoljeno; ako nije, primenjuje se pravilo o ponovljenom glasanju.",
    whatToCheck: [
      "Da li osoba poseduje formalno rešenje/potvrdu o članstvu u biračkom odboru",
      "Da li su ispunjeni svi ostali uslovi (identitet, spisak)",
    ],
    controllerActions: ["Proveriti dokument pre donošenja odluke", "Ne odbijati automatski, ali ni ne dozvoliti bez dokaza"],
    voterActions: ["Ponesi rešenje o imenovanju ako očekuješ ovu situaciju"],
    observerActions: ["Zabeleži kako je odbor postupio i na osnovu kog dokumenta"],
    evidenceChecklist: ["Da li je dokument pokazan", "Broj rešenja"],
    doNotDo: [],
    lawReferences: [ZINP_93],
    sourceUrls: [],
    relatedSlugs: ["ponovljeno-glasanje"],
    order: 14,
  },
  {
    id: "I03",
    slug: "nije-provalena-javna-isprava",
    naziv: "Identitet nije proveren odgovarajućom javnom ispravom",
    kategorija: "identitet_spisak",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birač dobija listić bez prethodne provere identiteta odgovarajućom javnom ispravom sa fotografijom i JMBG.",
    legalRule: "Identitet birača se utvrđuje ličnom kartom ili drugom odgovarajućom javnom ispravom sa fotografijom i JMBG.",
    legalEffect: "Proceduralna nepravilnost.",
    whatToCheck: ["Koji dokument je (ne)korišćen"],
    controllerActions: ["Zahtevati propisanu proveru pre izdavanja listića"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_93],
    sourceUrls: [],
    relatedSlugs: ["znamo-covjeka-ne-treba-licna"],
    order: 15,
  },
  {
    id: "I04",
    slug: "znamo-covjeka-ne-treba-licna",
    naziv: "„Znamo čoveka, ne treba mu lična karta“",
    kategorija: "identitet_spisak",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Član odbora izdaje listić samo na osnovu ličnog poznanstva, bez provere isprave.",
    legalRule: "Lično poznavanje birača ne zamenjuje propisanu proveru identiteta odgovarajućom javnom ispravom.",
    legalEffect: "Proceduralna nepravilnost, bez obzira na dobru nameru.",
    whatToCheck: [],
    controllerActions: ["Insistirati na proveri isprave kod svakog birača, bez izuzetka"],
    voterActions: ["Ponudi ličnu kartu i kad te član odbora poznaje"],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_93],
    sourceUrls: [],
    relatedSlugs: ["nije-provalena-javna-isprava"],
    mythCheck: {
      claim: "Član biračkog odbora sme da propusti proveru lične karte ako lično poznaje birača.",
      verdict: "mit",
      explanation: "Poznavanje birača ne zamenjuje propisanu proveru identiteta odgovarajućom javnom ispravom.",
    },
    order: 16,
  },
  {
    id: "I05",
    slug: "birac-nije-u-izvodu-dobija-listic",
    naziv: "Glasa lice koje nije upisano u izvod biračkog spiska",
    kategorija: "identitet_spisak",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Biračko mesto omogućava da glasa osoba koja se ne nalazi u izvodu iz biračkog spiska.",
    legalRule: "Birač mora biti upisan u izvod biračkog spiska za to biračko mesto da bi mogao da glasa na njemu.",
    legalEffect:
      "Ovo je jedan od zakonom izričito propisanih razloga za poništavanje glasanja na biračkom mestu po službenoj dužnosti.",
    whatToCheck: ["Da li je moguće da je osoba upisana na drugom biračkom mestu ili u drugom delu spiska"],
    controllerActions: [
      "Ne izdavati listić licu koje nije u izvodu",
      "Uputiti birača da proveri svoj status preko lokalne izborne komisije",
      "Uneti događaj u zapisnik ako je do izdavanja ipak došlo",
    ],
    voterActions: ["Proveri svoj upis u birački spisak pre dana glasanja preko nadležnog organa"],
    observerActions: ["Zabeleži slučaj i traži da bude unet u zapisnik"],
    evidenceChecklist: ["Ime lica (samo ako je zaista neophodno)", "Vreme", "Kako je odbor postupio"],
    doNotDo: [],
    lawReferences: [ZINP_116],
    sourceUrls: [],
    relatedSlugs: ["rucno-dopisivanje-biraca"],
    isAutomaticAnnulment: true,
    order: 17,
  },
  {
    id: "I06",
    slug: "rucno-dopisivanje-biraca",
    naziv: "Član odbora ručno dopisuje birača u spisak",
    kategorija: "identitet_spisak",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birački odbor pokušava da ručno dopiše osobu koja nije u izvodu, čak i ako smatra da je izostavljena greškom.",
    legalRule:
      "Birački odbor ne sme dopisivati birače u izvod, čak ni kada svi članovi smatraju da je birač očigledno izostavljen greškom.",
    legalEffect: "Zabranjena radnja; ako birač ipak glasa na osnovu dopisivanja, otvara se osnov za poništavanje.",
    whatToCheck: [],
    controllerActions: ["Odbiti dopisivanje", "Uputiti birača na nadležni organ za hitno rešavanje statusa"],
    voterActions: ["Ako te izostave iz spiska, obrati se odmah lokalnoj izbornoj komisiji, ne odboru"],
    observerActions: ["Zabeleži pokušaj dopisivanja"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_89],
    sourceUrls: [],
    relatedSlugs: ["birac-nije-u-izvodu-dobija-listic"],
    order: 18,
  },
  {
    id: "I07",
    slug: "vec-postoji-potpis-pored-imena",
    naziv: "Birač zatiče potpis kod svog imena iako nije glasao",
    kategorija: "identitet_spisak",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birač dolazi da glasa i primećuje da već postoji potpis pored njegovog imena u izvodu.",
    legalRule:
      "Potpis birača u izvodu treba da postoji samo ako je taj birač lično glasao. Neslaganje treba odmah proveriti i evidentirati.",
    legalEffect:
      "Visoko prioritetna nepravilnost, treba je odmah prijaviti lokalnoj izbornoj komisiji. Samo postojanje potpisa nije samo po sebi dokaz zloupotrebe dok se ne provere okolnosti.",
    whatToCheck: ["Da li je moguća greška u redu/prepisu imena", "Da li postoji evidencija da je birač navodno glasao"],
    controllerActions: ["Zaustaviti dalje postupanje i odmah kontaktirati lokalnu izbornu komisiju"],
    voterActions: [
      "Zatraži da se slučaj odmah zabeleži",
      "Nakon izbora zatraži od lokalne izborne komisije informaciju da li je evidentirano da si glasao",
    ],
    observerActions: ["Zabeleži tačno vreme i reakciju odbora"],
    evidenceChecklist: ["Ime (samo birača kog se tiče, uz njegov pristanak)", "Vreme", "Ko je obavešten"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 19,
  },
  {
    id: "I08",
    slug: "listic-urucen-pre-potpisa",
    naziv: "Listić uručen pre potpisa birača",
    kategorija: "identitet_spisak",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birač dobija glasački listić pre nego što se potpiše u izvodu.",
    legalRule: "Propisani redosled je: zaokruživanje rednog broja u izvodu, potpis birača, UV sprej, pa tek onda jedan glasački listić.",
    legalEffect: "Proceduralna nepravilnost.",
    whatToCheck: [],
    controllerActions: ["Ispraviti redosled radnji"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_93],
    sourceUrls: [],
    relatedSlugs: ["nema-potpisa-a-dobija-listic"],
    order: 20,
  },
  {
    id: "I09",
    slug: "nema-potpisa-a-dobija-listic",
    naziv: "Birač nije potpisan, a dobija listić",
    kategorija: "identitet_spisak",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birač uopšte nije potpisao izvod biračkog spiska, a ipak je dobio glasački listić.",
    legalRule: "Potpis birača u izvodu je preduslov za izdavanje listića.",
    legalEffect: "Broj potpisa kasnije služi za utvrđivanje broja birača koji su glasali i poredi se sa brojem listića u kutiji. Izostanak potpisa narušava tu kontrolu.",
    whatToCheck: [],
    controllerActions: ["Zaustaviti praksu odmah", "Uneti primedbu u zapisnik"],
    voterActions: [],
    observerActions: ["Zabeleži broj slučajeva"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_93, ZINP_116],
    sourceUrls: [],
    relatedSlugs: ["vise-listica-u-kutiji-nego-biraca"],
    order: 21,
  },
  {
    id: "I10",
    slug: "preskocen-uv-sprej",
    naziv: "Preskočeno obeležavanje UV sprejom",
    kategorija: "identitet_spisak",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Birač dobija listić bez prethodnog obeležavanja prsta UV sprejom.",
    legalRule: "UV sprej se nanosi nakon potpisa birača, pre uručenja glasačkog listića.",
    legalEffect: "Proceduralna nepravilnost, slabi zaštitu od ponovljenog glasanja.",
    whatToCheck: [],
    controllerActions: ["Zahtevati doslednu primenu kod svakog birača"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_93],
    sourceUrls: [],
    relatedSlugs: ["preskocena-uv-provera"],
    order: 22,
  },
  {
    id: "I11",
    slug: "dva-listica-jednom-biracu",
    naziv: "Jednom biraču data dva ili više glasačkih listića",
    kategorija: "identitet_spisak",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Član biračkog odbora uruči jednom biraču više od jednog glasačkog listića.",
    legalRule: "Birač dobija tačno jedan glasački listić.",
    legalEffect:
      "Krivični zakonik kažnjava korišćenje više od jednog glasačkog listića, kao i člana biračkog odbora koji to omogući. Za člana odbora predviđena je stroža kazna.",
    whatToCheck: [],
    controllerActions: ["Sprečiti i prijaviti odmah predsedniku odbora"],
    voterActions: [],
    observerActions: ["Prijaviti nadležnim organima"],
    evidenceChecklist: ["Vreme", "Ko je uručio", "Ko je primio"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 157 · Zloupotreba prava glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: [],
    order: 23,
  },
  {
    id: "I12",
    slug: "glasanje-pod-tudjim-imenom",
    naziv: "Glasanje pod tuđim imenom",
    kategorija: "identitet_spisak",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Osoba pokušava ili uspeva da glasa koristeći identitet drugog birača.",
    legalRule: "Glasanje je strogo lično i vezano za sopstveni identitet birača.",
    legalEffect: "Krivično delo prema Krivičnom zakoniku.",
    whatToCheck: [],
    controllerActions: [
      "Odbiti izdavanje listića pod tuđim imenom",
      "Ne ulaziti u fizički sukob niti samostalno zadržavati lice; obavestiti predsednika odbora i pozvati policiju kada okolnosti to zahtevaju",
    ],
    voterActions: [],
    observerActions: ["Prijaviti policiji"],
    evidenceChecklist: ["Identitet lica", "Vreme", "Svedoci"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 157 · Zloupotreba prava glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: [],
    order: 24,
  },
  {
    id: "I13",
    slug: "ponovljeno-glasanje",
    naziv: "Pokušaj ponovnog glasanja iste osobe",
    kategorija: "identitet_spisak",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Osoba koja je već glasala pokušava da ponovo glasa, uključujući na drugom biračkom mestu.",
    legalRule: "Birač glasa samo jednom, na biračkom mestu gde je upisan u izvod.",
    legalEffect: "Krivično delo prema Krivičnom zakoniku, osim u zakonom predviđenom izuzetku (npr. član biračkog odbora sa UV tragom i dokazom).",
    whatToCheck: ["Da li postoji zakonski izuzetak (vidi UV trag kod člana odbora)"],
    controllerActions: ["Odbiti drugo glasanje", "Prijaviti slučaj"],
    voterActions: [],
    observerActions: ["Prijaviti nadležnim organima"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 157 · Zloupotreba prava glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: ["uv-trag-clan-biracke-komisije-izuzetak"],
    order: 25,
  },

  // ---------------- TAJNOST I SLOBODA GLASANJA ----------------
  {
    id: "T01",
    slug: "grupno-porodicno-glasanje",
    naziv: "Grupno ili porodično glasanje bez zakonskog osnova",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Dvoje ili više ljudi ulazi zajedno iza paravana, bez zakonskog osnova za pomoć birača.",
    legalRule:
      "Birač glasa sam. Izuzetak postoji samo ako birač zbog nepismenosti, slabovidosti, invaliditeta ili drugog razloga nije sposoban da sam popuni listić: tada sam bira pomagača.",
    legalEffect: "Bez ispunjenog zakonskog uslova za pomagača, ovo je teška povreda tajnosti i slobode glasanja.",
    whatToCheck: ["Da li birač ima stvarnu potrebu za pomagačem", "Da li je birač sam odredio ko mu pomaže"],
    controllerActions: ["Proveriti osnov pre nego što dozvoliš zajednički ulazak", "Uneti primedbu ako osnova nema"],
    voterActions: ["Glasaj sam ako ti pomoć nije zaista potrebna"],
    observerActions: ["Zabeleži broj i okolnosti slučajeva"],
    evidenceChecklist: ["Vreme", "Da li je odbor proverio osnov"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["pomagac-samostalno-odlucuje", "neko-drugi-bira-pomagaca"],
    order: 26,
  },
  {
    id: "T02",
    slug: "pomagac-samostalno-odlucuje",
    naziv: "Pomagač samostalno određuje za koga se glasa",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Osoba koja pomaže biraču (npr. dete roditelju) sama odlučuje kako će listić biti popunjen.",
    legalRule: "Pomagač sme isključivo da tehnički popuni listić prema izričitom nalogu birača. Ne sme sam birati opciju.",
    legalEffect: "Povreda slobode glasanja birača kome se pomaže.",
    whatToCheck: ["Da li je birač jasno saopštio svoj izbor pomagaču"],
    controllerActions: ["Prekinuti postupak ako pomagač očigledno odlučuje umesto birača"],
    voterActions: ["Insistiraj da pomagač uradi tačno ono što mu kažeš"],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["grupno-porodicno-glasanje"],
    mythCheck: {
      claim: "Svaka pomoć starijoj ili bolesnoj osobi iza paravana je zabranjena.",
      verdict: "zavisi",
      explanation:
        "Zakon predviđa institut pomagača za birače koji zaista ne mogu sami da popune listić, pod uslovom da birač sam odredi pomagača i da pomagač samo izvršava njegov nalog.",
    },
    order: 27,
  },
  {
    id: "T03",
    slug: "clan-odbora-sugerise-broj-liste",
    naziv: "Član biračkog odbora sugeriše broj liste",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Član biračkog odbora govori biraču koji broj/listu da zaokruži.",
    legalRule: "Niko na biračkom mestu ne sme sugerisati biraču za koga da glasa.",
    legalEffect: "Teška povreda slobode i tajnosti glasanja, posebno ozbiljna jer dolazi od službenog lica.",
    whatToCheck: [],
    controllerActions: ["Odmah prekinuti takvo ponašanje i uneti primedbu u zapisnik"],
    voterActions: ["Ne moraš da poslušaš: glasaj po sopstvenom izboru i prijavi slučaj"],
    observerActions: ["Zabeleži tačne reči i okolnosti"],
    evidenceChecklist: ["Vreme", "Ko je izgovorio", "Svedoci"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["drugi-birac-sugerise-izbor"],
    order: 28,
  },
  {
    id: "T04",
    slug: "drugi-birac-sugerise-izbor",
    naziv: "Drugi birač ili treće lice sugeriše izbor",
    kategorija: "tajnost_sloboda",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Neko ko nije član odbora (drugi birač, posmatrač, treće lice) sugeriše biraču kako da glasa.",
    legalRule: "Zabrana sugerisanja izbora važi za sva lica na biračkom mestu, ne samo za članove odbora.",
    legalEffect: "Nepravilnost koju treba prekinuti odmah, bez obzira ko je izvršilac.",
    whatToCheck: [],
    controllerActions: ["Upozoriti lice i po potrebi ga udaljiti sa mesta"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["clan-odbora-sugerise-broj-liste"],
    order: 29,
  },
  {
    id: "T05",
    slug: "neko-stoji-uz-paravan",
    naziv: "Neko stoji uz paravan dok birač glasa",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Treće lice stoji neposredno uz paravan dok birač popunjava listić.",
    legalRule: "Niko ne sme da prilazi paravanu dok birač glasa, osim zakonitog pomagača kada je to zaista potrebno.",
    legalEffect: "Povreda tajnosti glasanja.",
    whatToCheck: [],
    controllerActions: ["Udaljiti lice od paravana"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["clan-odbora-gleda-preko-paravana"],
    order: 30,
  },
  {
    id: "T06",
    slug: "clan-odbora-gleda-preko-paravana",
    naziv: "Član biračkog odbora gleda kako birač glasa",
    kategorija: "tajnost_sloboda",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Član biračkog odbora namerno posmatra kako birač popunjava listić.",
    legalRule: "Tajnost glasanja je zaštićena; član odbora ne sme videti kako birač glasa.",
    legalEffect: "Krivično delo povrede tajnosti glasanja, sa težim oblikom kada delo izvrši član biračkog odbora u vršenju dužnosti.",
    whatToCheck: [],
    controllerActions: ["Prijaviti predsedniku odbora i nadležnim organima"],
    voterActions: [],
    observerActions: ["Prijaviti nadležnim organima"],
    evidenceChecklist: ["Vreme", "Svedoci", "Opis položaja"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 160 · Povreda tajnosti glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: ["neko-stoji-uz-paravan"],
    order: 31,
  },
  {
    id: "T07",
    slug: "zahtev-da-pokaze-glas",
    naziv: "Od birača se traži da pokaže za koga je glasao",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Neko traži od birača da pokaže listić ili na drugi način otkrije svoj izbor pre ubacivanja u kutiju.",
    legalRule: "Glasanje je tajno; niko nema pravo da traži od birača da otkrije svoj izbor.",
    legalEffect: "Teška povreda tajnosti glasanja; u zavisnosti od okolnosti (pretnja, korist) može dodatno predstavljati krivično delo.",
    whatToCheck: ["Da li je zahtev praćen pretnjom ili obećanjem koristi"],
    controllerActions: ["Prekinuti pokušaj, obavestiti predsednika odbora"],
    voterActions: ["Nisi dužan da pokažeš listić bilo kome"],
    observerActions: ["Zabeleži okolnosti"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["trazi-se-fotografija-kao-dokaz", "pretnja-biracu"],
    order: 32,
  },
  {
    id: "T08",
    slug: "trazi-se-fotografija-kao-dokaz",
    naziv: "Od birača se traži fotografija listića kao „dokaz“",
    kategorija: "tajnost_sloboda",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Neko van ili unutar biračkog mesta traži da birač fotografiše listić kao dokaz kako je glasao.",
    legalRule: "Ovakav zahtev ugrožava tajnost glasanja; ako je povezan sa korišću ili pretnjom, može predstavljati i posebno krivično delo.",
    legalEffect: "Ozbiljna crvena zastavica: u kombinaciji sa novcem, pretnjom ili pritiskom može predstavljati mito ili prinudu.",
    whatToCheck: ["Da li postoji ponuđena korist", "Da li postoji pretnja", "Ko postavlja zahtev"],
    controllerActions: ["Prijaviti predsedniku odbora", "Ne dozvoliti fotografisanje unutar biračkog mesta"],
    voterActions: ["Ne moraš da postupiš po ovakvom zahtevu; prijavi ga"],
    observerActions: ["Zabeleži okolnosti bez fotografisanja unutrašnjosti mesta"],
    evidenceChecklist: ["Ko je tražio", "Šta je obećano ili zaprećeno"],
    doNotDo: ["Ne savetuj biraču da fotografiše listić unutar biračkog mesta"],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["birac-sam-fotografise-listic", "kupovina-glasova", "pretnja-biracu"],
    order: 33,
  },
  {
    id: "T09",
    slug: "birac-sam-fotografise-listic",
    naziv: "Birač sam fotografiše svoj listić",
    kategorija: "tajnost_sloboda",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Birač bez spoljnog zahteva sam fotografiše svoj popunjeni listić.",
    legalRule: "Neovlašćeno fotografisanje na biračkom mestu tretira se kao narušavanje reda.",
    legalEffect: "Problematično ponašanje, ali samo po sebi nije dokaz kupovine glasova.",
    whatToCheck: [],
    controllerActions: ["Upozoriti birača na pravila o snimanju na biračkom mestu"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["trazi-se-fotografija-kao-dokaz"],
    mythCheck: {
      claim: "Ako neko fotografiše svoj listić, to samo po sebi dokazuje da je prodao glas.",
      verdict: "mit",
      explanation:
        "Posmatračke misije ovakve slučajeve beleže kao proceduralne probleme, ali fotografija sama po sebi ne dokazuje kupovinu glasa. Potrebni su dodatni dokazi o koristi ili pritisku.",
    },
    order: 34,
  },
  {
    id: "T10",
    slug: "pretnja-biracu",
    naziv: "Pretnja ili prinuda prema biraču",
    kategorija: "tajnost_sloboda",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Nekome se preti ili se koristi sila da glasa, ne glasa, ili glasa na određeni način.",
    legalRule: "Upotreba sile ili pretnje radi prisiljavanja nekoga da glasa, ne glasa ili glasa na određeni način je zabranjena.",
    legalEffect: "Krivično delo povrede prava glasanja.",
    whatToCheck: [],
    controllerActions: ["Prijaviti policiji"],
    voterActions: ["Prijavi pretnju policiji ili tužilaštvu što pre"],
    observerActions: ["Zabeleži okolnosti i svedoke"],
    evidenceChecklist: ["Ko je pretio", "Šta je tačno rečeno", "Svedoci"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 155 · Povreda prava glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: ["pretnja-poslom", "prinuda-fotografija-i-glas"],
    order: 35,
  },
  {
    id: "T11",
    slug: "pretnja-poslom",
    naziv: "„Izgubićeš posao ako ne izađeš/ne glasaš kako treba“",
    kategorija: "tajnost_sloboda",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Poslodavac ili nadređeni preti otkazom ili drugom posledicom u vezi sa izlaskom ili načinom glasanja.",
    legalRule: "Prisiljavanje na glasanje, neglasanje ili glasanje na određeni način zabranjeno je bez obzira na sredstvo prinude.",
    legalEffect: "Krivično delo povrede prava glasanja.",
    whatToCheck: [],
    controllerActions: [
      "Ako si član odbora, bezbedno evidentiraj navod i obavesti predsednika odbora",
      "Ako postoji neposredna opasnost, pozovi policiju; ne ulazi u fizičku konfrontaciju",
    ],
    voterActions: ["Prijavi slučaj: pretnja poslom u vezi sa glasanjem je krivično delo"],
    observerActions: [],
    evidenceChecklist: ["Ko je pretio", "Kada i kako", "Svedoci/poruke"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 155 · Povreda prava glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: ["pretnja-biracu"],
    order: 36,
  },
  {
    id: "T12",
    slug: "prinuda-fotografija-i-glas",
    naziv: "Prinuda da se fotografiše i glasa za određenu opciju",
    kategorija: "tajnost_sloboda",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Kombinacija pretnje, zahteva za fotografijom i naloga za koga tačno da se glasa.",
    legalRule: "Ova kombinacija istovremeno ugrožava tajnost glasanja i slobodu odlučivanja birača.",
    legalEffect: "Krivično delo povrede prava glasanja, uz moguću povredu tajnosti glasanja.",
    whatToCheck: [],
    controllerActions: [
      "Ne ulaziti u fizički sukob; obavestiti predsednika odbora i sačuvati činjenice",
      "Ako postoji neposredna opasnost, pozvati policiju",
    ],
    voterActions: ["Prijavi slučaj policiji ili tužilaštvu"],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [
      { law: KZ, article: "čl. 155 · Povreda prava glasanja", url: KZ_URL },
      { law: KZ, article: "čl. 160 · Povreda tajnosti glasanja", url: KZ_URL },
    ],
    sourceUrls: [],
    relatedSlugs: ["pretnja-biracu", "trazi-se-fotografija-kao-dokaz"],
    order: 37,
  },

  // ---------------- KUPOVINA GLASOVA ----------------
  {
    id: "KG01",
    slug: "kupovina-glasova",
    naziv: "Kupovina glasova",
    kategorija: "kupovina_glasova",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["svaka"],
    summary:
      "Nekome je ponuđena, obećana ili data korist (novac, roba, usluga, posao, otpis duga i sl.) u zamenu za glasanje, neglasanje, ili glasanje za/protiv određene opcije.",
    legalRule:
      "Davanje i primanje bilo kakve koristi u zamenu za određeno ponašanje na izborima je zabranjeno, bilo da korist nudi ili traži birač ili treće lice.",
    legalEffect:
      "Krivično delo davanja i primanja mita u vezi sa glasanjem. Kažnjivo je i nuđenje/davanje/obećavanje koristi i njeno traženje/primanje; za člana biračkog odbora predviđen je stroži oblik.",
    whatToCheck: ["Da li je korist zaista ponuđena/data ili se radi o legalnoj aktivnosti (npr. organizovan prevoz)"],
    controllerActions: [
      "Ne prihvatati niti nuditi korist; zabeležiti šta je ponuđeno i ko je učestvovao",
      "Bez direktne konfrontacije obavestiti nadležnu izbornu komisiju ili policiju",
    ],
    voterActions: ["Ne prihvatati ponudu, prijaviti nadležnim organima"],
    observerActions: ["Zabeleži okolnosti, izbegavaj direktnu konfrontaciju"],
    evidenceChecklist: ["Ko je nudio", "Šta je nuđeno", "Kada", "Svedoci"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 156 · Davanje i primanje mita u vezi sa glasanjem", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: ["trazi-se-fotografija-kao-dokaz"],
    mythCheck: {
      claim: "Organizovan prevoz birača do biračkog mesta je sam po sebi dokaz kupovine glasova.",
      verdict: "zavisi",
      explanation:
        "Sam prevoz nije automatski dokaz kupovine glasa. Potrebno je da postoji stvarno nuđenje, obećanje ili davanje koristi u zamenu za određeno glasanje.",
    },
    order: 38,
  },

  // ---------------- PARALELNA EVIDENCIJA ----------------
  {
    id: "E01",
    slug: "crtice-ukupne-izlaznosti",
    naziv: "Član odbora vodi brojčanu evidenciju izlaznosti (crtice)",
    kategorija: "paralelna_evidencija",
    severity: "dozvoljeno",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Član biračkog odbora zadužen za spisak vodi na posebnom papiru crtice, samo broj birača koji su izašli.",
    legalRule:
      "Članovi odbora zaduženi za birački spisak mogu na posebnom papiru voditi samo brojčanu evidenciju izlaznosti crticama, dostupnu svim članovima odbora.",
    legalEffect: "Dozvoljena, legitimna administrativna praksa.",
    whatToCheck: ["Da li je podatak zaista samo brojčani i dostupan svim članovima"],
    controllerActions: [],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["spisak-sa-imenima-ko-je-glasao"],
    mythCheck: {
      claim: "Svaka beleška odbora o broju izašlih birača je nezakonita paralelna evidencija.",
      verdict: "mit",
      explanation: "Brojčana evidencija crticama, dostupna svim članovima odbora, je izričito dozvoljena.",
    },
    order: 39,
  },
  {
    id: "E02",
    slug: "spisak-sa-imenima-ko-je-glasao",
    naziv: "Neslužbeni spisak sa imenima ko je (nije) glasao",
    kategorija: "paralelna_evidencija",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Neko na biračkom mestu vodi spisak sa konkretnim imenima birača koji jesu ili nisu izašli.",
    legalRule: "Zabranjeno je praviti neslužbene spiskove birača koji jesu ili nisu izašli na izbore.",
    legalEffect: "Nepravilnost: narušavanje reda i potencijalna osnova za pritisak na birače.",
    whatToCheck: [],
    controllerActions: ["Zahtevati prestanak i uklanjanje spiska"],
    voterActions: [],
    observerActions: ["Zabeleži ko vodi spisak i za koga"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["crtice-ukupne-izlaznosti", "telefonom-javljanje-ko-je-glasao"],
    order: 40,
  },
  {
    id: "E03",
    slug: "telefonom-javljanje-ko-je-glasao",
    naziv: "Telefonsko javljanje ko je konkretno glasao",
    kategorija: "paralelna_evidencija",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Neko telefonom prenosi podatke o tome koje konkretne osobe jesu ili nisu izašle na glasanje.",
    legalRule: "Zabranjeno je neovlašćeno davanje obaveštenja o tome koja konkretna lica jesu ili nisu izašla na izbore.",
    legalEffect: "Nepravilnost: narušavanje reda na biračkom mestu.",
    whatToCheck: [],
    controllerActions: ["Zahtevati prestanak", "Uneti u zapisnik"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["spisak-sa-imenima-ko-je-glasao"],
    order: 41,
  },
  {
    id: "E04",
    slug: "saopstavanje-samo-ukupne-izlaznosti",
    naziv: "Saopštava se samo zbirni broj izašlih birača",
    kategorija: "paralelna_evidencija",
    severity: "dozvoljeno",
    electionTypes: SVI,
    phases: ["identifikacija"],
    summary: "Član odbora saopštava samo ukupan broj birača koji su do tog trenutka glasali, bez imena.",
    legalRule: "Zbirni, brojčani podatak o izlaznosti dostupan svim članovima odbora je dozvoljen.",
    legalEffect: "Dozvoljeno.",
    whatToCheck: [],
    controllerActions: [],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["crtice-ukupne-izlaznosti"],
    order: 42,
  },

  // ---------------- NEOVLAŠĆENA LICA ----------------
  {
    id: "N01",
    slug: "nepoznata-osoba-bez-legitimacije",
    naziv: "Nepoznata osoba boravi na biračkom mestu bez osnova",
    kategorija: "neovlascena_lica",
    severity: "proveri",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Osoba koja nije birač, član odbora ni akreditovani posmatrač zadržava se na biračkom mestu.",
    legalRule: "Zadržavanje lica koja nemaju pravo ni dužnost u vezi sa sprovođenjem izbora predstavlja narušavanje reda.",
    legalEffect: "Ako lice nema osnov, radi se o nepravilnosti; akreditovani posmatrač je izuzetak i ima pravo prisustva.",
    whatToCheck: ["Da li osoba ima akreditaciju posmatrača ili drugi zakonski osnov"],
    controllerActions: ["Proveriti osnov prisustva", "Udaljiti lice bez osnova"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: ["Ko je lice", "Osnov (ili odsustvo osnova) prisustva"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["posmatracu-onemoguceno-pracenje-brojanja"],
    order: 43,
  },
  {
    id: "N02",
    slug: "posmatracu-onemoguceno-pracenje-brojanja",
    naziv: "Akreditovanom posmatraču se onemogućava praćenje brojanja",
    kategorija: "neovlascena_lica",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["brojanje"],
    summary: "Birački odbor sprečava akreditovanog posmatrača da prati otvaranje kutije i prebrojavanje.",
    legalRule:
      "Akreditovani posmatrač ima pravo da nesmetano prati rad biračkog odbora, od preuzimanja materijala, preko glasanja, do otvaranja kutije, brojanja i predaje materijala.",
    legalEffect: "Ozbiljna nepravilnost koja ograničava zakonom predviđeno posmatranje rada biračkog odbora.",
    whatToCheck: ["Da li posmatrač ima važeću akreditaciju"],
    controllerActions: ["Omogućiti nesmetano posmatranje u skladu sa pravilima reda"],
    voterActions: [],
    observerActions: ["Zahtevati unos primedbe u sopstveni zapisnik posmatrača"],
    evidenceChecklist: ["Vreme", "Ko je sprečio", "Kako"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["nepoznata-osoba-bez-legitimacije"],
    order: 44,
  },
  {
    id: "N03",
    slug: "posmatrac-krsi-pravila-ponasanja",
    naziv: "Posmatrač koristi telefon ili ometa rad odbora",
    kategorija: "neovlascena_lica",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["glasanje"],
    summary: "Akreditovani posmatrač ne poštuje pravila reda: koristi sredstva komunikacije ili ometa rad odbora.",
    legalRule: "Posmatrač mora poštovati pravila reda; birački odbor može udaljiti posmatrača koji ih krši.",
    legalEffect: "Posmatrač snosi posledice kršenja pravila; ne utiče automatski na ispravnost samog glasanja.",
    whatToCheck: [],
    controllerActions: ["Upozoriti posmatrača", "Udaljiti ako se ponašanje nastavi"],
    voterActions: [],
    observerActions: ["Poštuj zabrane korišćenja telefona i komunikacije na biračkom mestu"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 45,
  },

  // ---------------- BUGARSKI VOZ ----------------
  {
    id: "BV01",
    slug: "bugarski-voz",
    naziv: "Sumnja na organizovanu manipulaciju listićima („bugarski voz“)",
    kategorija: "bugarski_voz",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["svaka"],
    summary:
      "Naziv za oblik organizovane manipulacije u kojem se službeni glasački listić protivpravno iznosi iz normalnog toka glasanja i koristi za kontrolisano/cirkularno glasanje.",
    legalRule:
      "Iznošenje službenog glasačkog listića van propisanog toka glasanja i njegovo korišćenje van biračkog mesta je protivzakonito.",
    legalEffect: "Ozbiljna sumnja na organizovanu izbornu manipulaciju sa mogućim krivičnopravnim posledicama.",
    whatToCheck: [
      "Da li birač pokušava da napusti mesto sa glasačkim listićem",
      "Da li postoji službeni listić van mesta gde sme da bude",
      "Da li se broj izdatih, vraćenih i pronađenih listića ne slaže",
      "Da li neko van biračkog mesta traži od birača da donese ili pokaže listić",
    ],
    controllerActions: ["Sprečiti iznošenje listića sa biračkog mesta", "Odmah obavestiti nadležne organe"],
    voterActions: [],
    observerActions: ["Prijaviti sumnjive slučajeve policiji, kao što su to ranije radile akreditovane posmatračke organizacije"],
    evidenceChecklist: ["Vreme", "Opis situacije", "Svedoci", "Da li se računica listića slaže"],
    doNotDo: ["Ovaj vodič ne opisuje operativni način izvršenja, samo znake za prepoznavanje"],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["vise-listica-u-kutiji-nego-biraca"],
    order: 46,
  },

  // ---------------- GLASANJE VAN BIRAČKOG MESTA ----------------
  {
    id: "V01",
    slug: "samo-jedan-clan-odbora-kod-kuce",
    naziv: "Kod birača ide samo jedan član biračkog odbora",
    kategorija: "van_birackog_mesta",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Glasanju van biračkog mesta prisustvuje samo jedan član odbora umesto propisana tri.",
    legalRule: "Kod birača idu tri člana biračkog odbora, imenovana na predlog različitih ovlašćenih predlagača.",
    legalEffect: "Teška proceduralna nepravilnost koja dovodi u pitanje ispravnost postupka.",
    whatToCheck: [],
    controllerActions: ["Ne sprovoditi postupak dok se ne obezbede tri člana"],
    voterActions: [],
    observerActions: ["Zabeleži broj prisutnih članova"],
    evidenceChecklist: ["Broj prisutnih članova", "Vreme"],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: ["samo-dva-clana-odbora-kod-kuce"],
    order: 47,
  },
  {
    id: "V02",
    slug: "samo-dva-clana-odbora-kod-kuce",
    naziv: "Kod birača idu samo dva člana biračkog odbora",
    kategorija: "van_birackog_mesta",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Glasanju van biračkog mesta prisustvuju samo dva umesto propisana tri člana odbora.",
    legalRule: "Kod birača idu tri člana biračkog odbora, imenovana na predlog različitih ovlašćenih predlagača.",
    legalEffect: "Teška proceduralna nepravilnost.",
    whatToCheck: [],
    controllerActions: ["Ne sprovoditi postupak dok se ne obezbedi treći član"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: ["samo-jedan-clan-odbora-kod-kuce"],
    order: 48,
  },
  {
    id: "V03",
    slug: "poverenici-isti-predlagac",
    naziv: "Sva tri poverenika pripadaju istom predlagaču",
    kategorija: "van_birackog_mesta",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Tri člana koja idu kod birača nisu imenovana na predlog različitih ovlašćenih predlagača.",
    legalRule: "Tri člana koja sprovode glasanje van biračkog mesta moraju biti imenovana na predlog različitih ovlašćenih predlagača.",
    legalEffect: "Nepravilnost koja ugrožava nepristrasnost postupka.",
    whatToCheck: ["Ko je predložio svakog od tri člana"],
    controllerActions: ["Zahtevati zamenu sastava pre sprovođenja postupka"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: [],
    order: 49,
  },
  {
    id: "V04",
    slug: "identitet-nije-proveren-kod-kuce",
    naziv: "Identitet birača nije proveren kod kuće",
    kategorija: "van_birackog_mesta",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Poverenici ne provere identitet birača pre glasanja van biračkog mesta.",
    legalRule: "Identitet birača mora biti proveren i pri glasanju van biračkog mesta, na isti način kao na biračkom mestu.",
    legalEffect: "Teška proceduralna nepravilnost.",
    whatToCheck: [],
    controllerActions: ["Zahtevati proveru identiteta pre nastavka postupka"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: ["nema-uv-provere-kod-kuce"],
    order: 50,
  },
  {
    id: "V05",
    slug: "nema-uv-provere-kod-kuce",
    naziv: "UV provera nije sprovedena kod kuće",
    kategorija: "van_birackog_mesta",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Poverenici ne sprovedu UV proveru i obeležavanje prsta pri glasanju van biračkog mesta.",
    legalRule: "UV provera i obeležavanje su deo propisanog postupka i pri glasanju van biračkog mesta.",
    legalEffect: "Proceduralna nepravilnost.",
    whatToCheck: [],
    controllerActions: ["Zahtevati sprovođenje kompletne procedure"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: ["identitet-nije-proveren-kod-kuce"],
    order: 51,
  },
  {
    id: "V06",
    slug: "nema-potpisane-potvrde-kod-kuce",
    naziv: "Birač nije potpisao potvrdu o glasanju van biračkog mesta",
    kategorija: "van_birackog_mesta",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Birač nije potpisao propisanu potvrdu, ali se njegov glas ipak uzima u obzir.",
    legalRule: "Bez potpisane potvrde o pravu glasanja van biračkog mesta, listić se ne ubacuje u glasačku kutiju.",
    legalEffect: "Ako se listić uprkos tome ubaci u kutiju, radi se o teškoj proceduralnoj nepravilnosti.",
    whatToCheck: ["Da li potvrda uopšte postoji i da li je potpisana"],
    controllerActions: ["Ne ubacivati listić u kutiju bez potpisane potvrde", "Uneti u zapisnik"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: ["Da li potvrda postoji", "Potpis birača"],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: [],
    order: 52,
  },
  {
    id: "V07",
    slug: "poverenici-ostaju-dok-birac-glasa",
    naziv: "Poverenici ostaju u prostoriji dok birač popunjava listić",
    kategorija: "van_birackog_mesta",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Nakon objašnjenja postupka, poverenici ne napuštaju prostoriju dok birač glasa.",
    legalRule: "Nakon objašnjenja postupka, poverenici napuštaju prostoriju u kojoj birač samostalno popunjava listić.",
    legalEffect: "Povreda tajnosti glasanja.",
    whatToCheck: [],
    controllerActions: ["Napustiti prostoriju tokom popunjavanja listića"],
    voterActions: ["Zatraži da poverenici izađu dok popunjavaš listić"],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: [],
    order: 53,
  },
  {
    id: "V08",
    slug: "neko-drugi-bira-pomagaca-kod-kuce",
    naziv: "Neko drugi umesto birača bira ko će mu pomoći",
    kategorija: "van_birackog_mesta",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Pomagača pri glasanju van biračkog mesta određuje neko drugi, a ne sam birač.",
    legalRule: "Birač sam određuje ko će mu pomoći, ako mu je pomoć zaista potrebna.",
    legalEffect: "Nepravilnost: povreda slobode izbora birača.",
    whatToCheck: [],
    controllerActions: ["Proveriti da li je birač sam izabrao pomagača"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: ["pomagac-samostalno-odlucuje"],
    order: 54,
  },
  {
    id: "V09",
    slug: "koverat-nije-zapecacen-pred-biracem",
    naziv: "Koverat sa listićem nije zapečaćen pred biračem",
    kategorija: "van_birackog_mesta",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["van_birackog_mesta"],
    summary: "Koverat sa popunjenim listićem se pečati van vidokruga birača.",
    legalRule: "Koverat se pečati pred biračem, neposredno nakon što popuni listić.",
    legalEffect: "Proceduralna nepravilnost koja otvara sumnju u ispravnost listića.",
    whatToCheck: [],
    controllerActions: ["Pečatiti koverat isključivo pred biračem"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_96],
    sourceUrls: [],
    relatedSlugs: [],
    order: 55,
  },

  // ---------------- ZATVARANJE ----------------
  {
    id: "Z01",
    slug: "izbacivanje-birača-u-redu",
    naziv: "Birači u redu u 20:00 ne dobijaju priliku da glasaju",
    kategorija: "zatvaranje",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["zatvaranje"],
    summary: "Birački odbor zatvara mesto tačno u 20:00 i odbija birače koji su već bili u redu ili na mestu.",
    legalRule: "Svi koji se u 20:00 nalaze na biračkom mestu ili neposredno ispred u redu moraju dobiti mogućnost da glasaju.",
    legalEffect: "Teška povreda biračkog prava birača u redu.",
    whatToCheck: ["Da li su birači zaista bili u redu do 20:00"],
    controllerActions: ["Omogućiti glasanje svima koji su bili u redu do 20:00"],
    voterActions: ["Ostani u redu i insistiraj na svom pravu ako si stigao pre 20:00"],
    observerActions: ["Zabeleži tačno vreme zatvaranja i broj odbijenih birača"],
    evidenceChecklist: ["Vreme", "Broj ljudi u redu", "Kako je odbor postupio"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 56,
  },
  {
    id: "Z02",
    slug: "kasnjenje-otvaranja-produzenje-glasanja",
    naziv: "Kasnilo je otvaranje: da li se glasanje produžava?",
    kategorija: "zatvaranje",
    severity: "proveri",
    electionTypes: SVI,
    phases: ["zatvaranje"],
    summary: "Biračko mesto je otvoreno kasnije od 07:00 ili je bilo prekida u radu.",
    legalRule: "Ako je otvaranje kasnilo ili je glasanje bilo prekinuto duže od sat vremena, vreme glasanja se produžava za odgovarajući period.",
    legalEffect: "Glasanje se ne zatvara mehanički u 20:00 ako je bilo kašnjenja ili dužeg prekida.",
    whatToCheck: ["Tačno vreme otvaranja", "Trajanje eventualnih prekida"],
    controllerActions: ["Izračunati i objaviti produženo vreme zatvaranja", "Uneti u zapisnik"],
    voterActions: [],
    observerActions: ["Zabeleži vreme otvaranja i sve prekide"],
    evidenceChecklist: ["Vreme otvaranja", "Trajanje prekida"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 57,
  },
  {
    id: "Z03",
    slug: "ranije-zatvaranje-svi-glasali",
    naziv: "Ranije zatvaranje kada su svi upisani birači glasali",
    kategorija: "zatvaranje",
    severity: "dozvoljeno",
    electionTypes: SVI,
    phases: ["zatvaranje"],
    summary: "Biračko mesto se zatvara pre 20:00 jer su svi birači iz izvoda već glasali.",
    legalRule: "Zakon dozvoljava ranije zatvaranje ako su glasali svi birači iz izvoda, ali rezultat se ne sme javno saopštiti ili istaći pre 20:00.",
    legalEffect: "Dozvoljeno, uz obavezu da se rezultat ne objavljuje pre zvaničnog vremena zatvaranja.",
    whatToCheck: ["Da li je zaista glasao svaki birač iz izvoda", "Da li je rezultat slučajno objavljen pre 20:00"],
    controllerActions: ["Ne saopštavati niti isticati rezultat pre 20:00"],
    voterActions: [],
    observerActions: ["Proveriti da rezultat nije prevremeno objavljen"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 58,
  },

  // ---------------- BROJANJE / AUTOMATSKO PONIŠTAVANJE ----------------
  {
    id: "AN01",
    slug: "vise-listica-u-kutiji-nego-biraca",
    naziv: "Više listića u kutiji nego birača koji su glasali",
    kategorija: "brojanje",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["brojanje"],
    summary: "Broj glasačkih listića pronađenih u kutiji veći je od broja birača koji su, prema potpisima, glasali.",
    legalRule: "Broj listića u kutiji ne sme biti veći od broja birača koji su glasali (utvrđenog preko potpisa i evidencije glasanja van biračkog mesta).",
    legalEffect: "Jedan od zakonom izričito propisanih razloga za poništavanje glasanja na biračkom mestu po službenoj dužnosti.",
    whatToCheck: ["Tačnost prebrojavanja potpisa", "Tačnost prebrojavanja listića u kutiji"],
    controllerActions: ["Ponovo prebrojati oba broja pre donošenja zaključka", "Uneti tačne brojeve u zapisnik"],
    voterActions: [],
    observerActions: ["Prati brojanje oba niza podataka"],
    evidenceChecklist: ["Broj potpisa", "Broj listića u kutiji"],
    doNotDo: [],
    lawReferences: [ZINP_116, ZINP_102],
    sourceUrls: [],
    relatedSlugs: ["kontrolni-list-nije-ubacen-u-kutiju", "nema-potpisa-a-dobija-listic"],
    isAutomaticAnnulment: true,
    order: 59,
  },
  {
    id: "AN02",
    slug: "neupotrebljeni-plus-kutija-veci-od-primljenih",
    naziv: "Neupotrebljeni listići + listići iz kutije > broj primljenih listića",
    kategorija: "brojanje",
    severity: "ponistavanje",
    electionTypes: SVI,
    phases: ["brojanje"],
    summary: "Zbir neiskorišćenih listića i listića pronađenih u kutiji veći je od broja listića koje je odbor primio.",
    legalRule: "Zbir neupotrebljenih listića i listića iz kutije ne sme biti veći od broja primljenih listića.",
    legalEffect: "Jedan od zakonom izričito propisanih razloga za poništavanje glasanja na biračkom mestu po službenoj dužnosti.",
    whatToCheck: ["Da li je broj primljenih listića tačno evidentiran na početku dana"],
    controllerActions: ["Ponovo prebrojati sve tri kategorije pre zaključka"],
    voterActions: [],
    observerActions: [],
    evidenceChecklist: ["Broj primljenih", "Broj neupotrebljenih", "Broj u kutiji"],
    doNotDo: [],
    lawReferences: [ZINP_116, ZINP_102],
    sourceUrls: [],
    relatedSlugs: ["vise-listica-u-kutiji-nego-biraca"],
    isAutomaticAnnulment: true,
    order: 60,
  },
  {
    id: "NR01",
    slug: "nemogucnost-utvrdjivanja-rezultata",
    naziv: "Nemogućnost utvrđivanja rezultata glasanja",
    kategorija: "brojanje",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["brojanje"],
    summary: "Postoji situacija u kojoj se rezultat glasanja na biračkom mestu uopšte ne može utvrditi.",
    legalRule:
      "Rezultat se ne može utvrditi kada, između ostalog: glasanje nije održano; glasanje je prekinuto i nije nastavljeno; komisija nije dobila zapisnik; zapisnik nije potpisalo najmanje tri člana biračkog odbora; postoje grube logičko-računske greške koje se ne mogu otkloniti ni pregledom kompletnog materijala.",
    legalEffect:
      "Ovo je pravno drugačija situacija od poništavanja po službenoj dužnosti, iako obe mogu voditi ponovljenom glasanju na tom mestu.",
    whatToCheck: [],
    controllerActions: ["Obezbediti da zapisnik potpiše najmanje tri člana odbora", "Odmah dostaviti zapisnik komisiji"],
    voterActions: [],
    observerActions: ["Zabeleži tačan razlog zbog kog rezultat nije mogao biti utvrđen"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["vise-listica-u-kutiji-nego-biraca"],
    order: 61,
  },

  // ---------------- ZAPISNIK ----------------
  {
    id: "ZP01",
    slug: "potpisivanje-praznog-zapisnika",
    naziv: "Od člana odbora se traži da potpiše prazan ili nepotpun zapisnik",
    kategorija: "zapisnik",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["zapisnik"],
    summary: "Član biračkog odbora se poziva da potpiše zapisnik pre nego što su svi relevantni podaci uneti i provereni.",
    legalRule: "Zapisnik mora sadržati sve propisane podatke (brojeve birača, listića, kontrolni list, prekide, primedbe) pre potpisivanja.",
    legalEffect: "Nikada ne potpisuj zapisnik čiji podaci nisu uneti i provereni.",
    whatToCheck: ["Da li su sva propisana polja popunjena i tačna"],
    controllerActions: ["Odbiti potpis dok podaci nisu kompletni i tačni", "Zahtevati vreme za proveru"],
    voterActions: [],
    observerActions: ["Prati da li se ovo dešava i uneti primedbu u sopstveni zapisnik"],
    evidenceChecklist: [],
    doNotDo: ["Ne potpisuj pod pritiskom vremena bez provere podataka"],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["treci-primerak-nije-istaknut"],
    order: 62,
  },
  {
    id: "ZP02",
    slug: "ne-dozvoljavaju-primedbu-u-zapisnik",
    naziv: "Članu odbora se ne dozvoljava da unese primedbu",
    kategorija: "zapisnik",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["zapisnik"],
    summary: "Predsednik odbora odbija da unese primedbu člana odbora u zapisnik.",
    legalRule: "Zapisnik izričito sadrži i primedbe članova biračkog odbora.",
    legalEffect: "Ozbiljna nepravilnost koja onemogućava pravnu zaštitu člana odbora.",
    whatToCheck: [],
    controllerActions: ["Insistirati na pravu da primedba bude uneta", "Sačuvati sopstvenu pisanu kopiju primedbe"],
    voterActions: [],
    observerActions: ["Iskoristi sopstveni zapisnik posmatrača za istu primedbu"],
    evidenceChecklist: [],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: [],
    order: 63,
  },
  {
    id: "ZP03",
    slug: "treci-primerak-nije-istaknut",
    naziv: "Treći primerak zapisnika nije javno istaknut",
    kategorija: "zapisnik",
    severity: "nepravilnost",
    electionTypes: SVI,
    phases: ["zapisnik"],
    summary: "Nakon završetka brojanja, treći primerak zapisnika nije istaknut na biračkom mestu na javni uvid.",
    legalRule: "Treći primerak zapisnika ističe se na biračkom mestu na javni uvid.",
    legalEffect: "Proceduralna nepravilnost: otežava javnu kontrolu rezultata.",
    whatToCheck: [],
    controllerActions: ["Istaći primerak odmah po završetku brojanja"],
    voterActions: [],
    observerActions: ["Fotografisati istaknuti zapisnik radi kasnijeg poređenja"],
    evidenceChecklist: ["Da li je i kada istaknut"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["rezultat-se-razlikuje-od-prebrojanog"],
    order: 64,
  },
  {
    id: "ZP04",
    slug: "rezultat-se-razlikuje-od-prebrojanog",
    naziv: "Objavljeni rezultat se razlikuje od onoga što je stvarno prebrojano",
    kategorija: "zapisnik",
    severity: "teska_nepravilnost",
    electionTypes: SVI,
    phases: ["zapisnik"],
    summary: "Brojevi u istaknutom ili objavljenom zapisniku ne odgovaraju onome što je zabeleženo tokom brojanja.",
    legalRule: "Zapisnik mora verno odražavati rezultat utvrđen prilikom brojanja.",
    legalEffect: "Ozbiljna nepravilnost; u zavisnosti od namere može predstavljati i falsifikovanje rezultata glasanja.",
    whatToCheck: ["Uporedi sopstvene beleške sa objavljenim zapisnikom broj po broj"],
    controllerActions: [],
    voterActions: [],
    observerActions: ["Uporedi svoje beleške sa istaknutim zapisnikom i prijavi neslaganje"],
    evidenceChecklist: ["Sopstvene beleške tokom brojanja", "Fotografija istaknutog zapisnika"],
    doNotDo: [],
    lawReferences: [ZINP_TOK],
    sourceUrls: [],
    relatedSlugs: ["namerno-menjanje-rezultata"],
    order: 65,
  },

  // ---------------- FALSIFIKOVANJE ----------------
  {
    id: "FR01",
    slug: "namerno-menjanje-rezultata",
    naziv: "Namerno menjanje rezultata glasanja",
    kategorija: "falsifikovanje",
    severity: "krivicno_delo",
    electionTypes: SVI,
    phases: ["zapisnik"],
    summary: "Član izbornog organa ili drugo lice u vezi sa glasanjem svesno menja broj glasova ili listića, ili objavljuje neistinit rezultat.",
    legalRule:
      "Dodavanje ili oduzimanje listića ili glasova, ili promena broja glasova ili objava neistinitog rezultata od strane člana izbornog organa ili drugog lica u vezi sa glasanjem je zabranjeno.",
    legalEffect:
      "Krivično delo falsifikovanja rezultata glasanja. Republička izborna komisija je dužna da podnese krivičnu prijavu ako postoji osnovana sumnja da veliko neslaganje materijala i zapisnika potiče od svesne i namerne aktivnosti radi utvrđivanja neistinitog rezultata.",
    whatToCheck: [],
    controllerActions: [
      "Ne menjati originalni materijal; sačuvati tačne brojke, primedbu i prateće dokaze",
      "Obavestiti nadležnu izbornu komisiju, a kod osnovane sumnje i javno tužilaštvo",
    ],
    voterActions: ["Prijavi neslaganje odmah nadležnoj izbornoj komisiji i, po potrebi, tužilaštvu"],
    observerActions: ["Sačuvaj sve beleške i dokaze o neslaganju brojeva"],
    evidenceChecklist: ["Sve zabeležene brojke tokom brojanja", "Fotografija istaknutog zapisnika", "Objavljeni zvanični rezultat"],
    doNotDo: [],
    lawReferences: [{ law: KZ, article: "čl. 161 · Falsifikovanje rezultata glasanja", url: KZ_URL }],
    sourceUrls: [],
    relatedSlugs: ["rezultat-se-razlikuje-od-prebrojanog"],
    order: 66,
  },
];

export const rulesById = new Map(rules.map((r) => [r.id, r]));
export const rulesBySlug = new Map(rules.map((r) => [r.slug, r]));

