import type { TrainingQuestion } from "@/lib/domain/training/types";

/**
 * Autorska pitanja: pisana ručno, sa stvarnim distraktorima i tagovima zabluda.
 * Generator (`generate-questions.ts`) samo dopunjava coverage tamo gde autorskih nema.
 */
export const authoredTrainingQuestions: TrainingQuestion[] = [
  // ------------------------------------------------------------------ REDOSLED I PROCEDURA
  {
    id: "A-I01-seq",
    ruleId: "I01",
    type: "sequence",
    prompt: "Poređaj propisani redosled radnji pre nego što birač dobije glasački listić.",
    choices: [
      { id: "uv", label: "Provera UV lampom", isCorrect: true, explanation: "UV provera je prva, pre nego što se uopšte otvori izvod." },
      { id: "id", label: "Utvrđivanje identiteta javnom ispravom", isCorrect: true, explanation: "Identitet se utvrđuje ispravom sa fotografijom i JMBG." },
      { id: "spisak", label: "Provera upisa u izvod biračkog spiska", isCorrect: true, explanation: "Bez upisa u izvod listić se ne izdaje." },
      { id: "potpis", label: "Zaokruživanje rednog broja i potpis birača", isCorrect: true, explanation: "Potpis prethodi izdavanju listića i kasnije služi za utvrđivanje izlaznosti." },
      { id: "sprej", label: "Obeležavanje prsta UV sprejom", isCorrect: true, explanation: "Sprej se nanosi posle potpisa, pre uručenja listića." },
      { id: "listic", label: "Uručenje jednog glasačkog listića", isCorrect: true, explanation: "Birač dobija tačno jedan listić, na kraju procedure." },
    ],
    correctOrder: ["uv", "id", "spisak", "potpis", "sprej", "listic"],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },
  {
    id: "A-AN01-seq",
    ruleId: "AN01",
    type: "sequence",
    prompt: "Poređaj radnje pri utvrđivanju rezultata na biračkom mestu, počev od zatvaranja.",
    choices: [
      { id: "birači", label: "Utvrđivanje broja birača koji su glasali (potpisi i evidencija van BM)", isCorrect: true, explanation: "Broj birača se utvrđuje pre otvaranja kutije." },
      { id: "neupotrebljeni", label: "Prebrojavanje neupotrebljenih listića", isCorrect: true, explanation: "Neiskorišćeni listići se prebrojavaju dok je kutija još zatvorena." },
      { id: "kutija", label: "Provera da je kutija ispravna i zapečaćena", isCorrect: true, explanation: "Stanje kutije se konstatuje pre otvaranja." },
      { id: "otvaranje", label: "Otvaranje kutije", isCorrect: true, explanation: "Kutija se otvara tek posle prethodne tri radnje." },
      { id: "kontrolni", label: "Pronalaženje kontrolnog lista", isCorrect: true, explanation: "Kontrolni list se traži odmah po otvaranju kutije." },
      { id: "razvrstavanje", label: "Razvrstavanje listića na važeće i nevažeće", isCorrect: true, explanation: "Razvrstavanje ide posle utvrđivanja da je kontrolni list u kutiji." },
    ],
    correctOrder: ["birači", "neupotrebljeni", "kutija", "otvaranje", "kontrolni", "razvrstavanje"],
    difficulty: "annulment",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },

  // ------------------------------------------------------------------ ZABLUDE
  {
    id: "A-T02-helper",
    ruleId: "T02",
    type: "true_false",
    prompt: "Slabovida birateljka sama zamoli svoju ćerku da joj popuni listić onako kako joj kaže. Odbor to mora da zabrani.",
    choices: [
      {
        id: "false",
        label: "Netačno - pomoć je dozvoljena pod zakonskim uslovima",
        isCorrect: true,
        explanation:
          "Birač koji zbog slabovidosti ne može sam da popuni listić ima pravo da sam odredi pomagača, a pomagač popunjava listić po njegovom nalogu.",
      },
      {
        id: "true",
        label: "Tačno - glasanje je strogo lično i pomoć nikada nije dozvoljena",
        isCorrect: false,
        explanation: "Institut pomagača postoji upravo za birače koji ne mogu sami da popune listić.",
        misconception: "HELPER_ALWAYS_ILLEGAL",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["HELPER_ALWAYS_ILLEGAL"],
    authored: true,
  },
  {
    id: "A-T02-helper-scenario",
    ruleId: "T01",
    type: "scenario",
    prompt:
      "Sin dolazi sa majkom, ulazi sa njom iza paravana i sam bira broj liste jer „ona ionako ne razume“. Šta je ovde odlučujuće?",
    choices: [
      {
        id: "correct",
        label: "Nedozvoljeno je: pomagač sme samo da izvrši nalog birača, ne da odluči umesto njega",
        isCorrect: true,
        explanation:
          "Pomagač popunjava listić isključivo prema izričitom nalogu birača; odlučivanje umesto birača je povreda slobode glasanja.",
      },
      {
        id: "wrong-family",
        label: "Dozvoljeno je jer je reč o članu porodice",
        isCorrect: false,
        explanation: "Srodstvo ne daje pravo da neko drugi odluči kako će listić biti popunjen.",
        misconception: "HELPER_ALWAYS_ILLEGAL",
      },
      {
        id: "wrong-ban",
        label: "Nedozvoljeno je jer nijedna pomoć iza paravana nije dopuštena",
        isCorrect: false,
        explanation:
          "Zaključak je tačan, ali obrazloženje nije: pomoć jeste dozvoljena kada birač ne može sam i kada sam odredi pomagača.",
        misconception: "HELPER_ALWAYS_ILLEGAL",
      },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["HELPER_ALWAYS_ILLEGAL"],
    authored: true,
  },
  {
    id: "A-E01-tally",
    ruleId: "E01",
    type: "classification",
    prompt:
      "Član odbora zadužen za birački spisak vodi na posebnom papiru samo crtice, bez ijednog imena, i podatak je dostupan svim članovima. Kako to klasifikuješ?",
    choices: [
      {
        id: "allowed",
        label: "Dozvoljeno",
        isCorrect: true,
        explanation: "Brojčana evidencija izlaznosti crticama, dostupna svim članovima odbora, izričito je dozvoljena.",
      },
      {
        id: "irregular",
        label: "Nepravilnost - svaka evidencija je paralelni spisak",
        isCorrect: false,
        explanation: "Zabranjeni su spiskovi sa imenima onih koji jesu ili nisu izašli, ne i zbirni broj.",
        misconception: "TALLY_MARKS_ALWAYS_ILLEGAL",
      },
      {
        id: "criminal",
        label: "Moguće krivično delo",
        isCorrect: false,
        explanation: "Ovakva evidencija nema obeležja krivičnog dela; ona je deo redovnog rada odbora.",
        misconception: "TALLY_MARKS_ALWAYS_ILLEGAL",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["TALLY_MARKS_ALWAYS_ILLEGAL"],
    authored: true,
  },
  {
    id: "A-E02-list",
    ruleId: "E02",
    type: "classification",
    prompt:
      "Na istom papiru, pored crtica, vodi se i kolona sa imenima birača koji do 16 časova nisu izašli. Kako to klasifikuješ?",
    choices: [
      {
        id: "irregular",
        label: "Nepravilnost",
        isCorrect: true,
        explanation: "Pravljenje neslužbenih spiskova birača koji jesu ili nisu izašli zakon navodi kao narušavanje reda.",
      },
      {
        id: "allowed",
        label: "Dozvoljeno, jer je i to samo evidencija",
        isCorrect: false,
        explanation: "Razlika je upravo u imenima: zbirni broj je dozvoljen, poimenični spisak nije.",
        misconception: "TALLY_MARKS_ALWAYS_ILLEGAL",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["TALLY_MARKS_ALWAYS_ILLEGAL"],
    authored: true,
  },
  {
    id: "A-I06-add",
    ruleId: "I06",
    type: "true_false",
    prompt:
      "Svi članovi odbora se slažu da je birač očiglednom greškom izostavljen iz izvoda. U tom slučaju smeju da ga dopišu.",
    choices: [
      {
        id: "false",
        label: "Netačno - dopisivanje nije dozvoljeno ni uz jednoglasnu odluku",
        isCorrect: true,
        explanation: "Birački odbor ne sme dopisivati birače u izvod, čak ni kada smatra da je birač izostavljen greškom.",
      },
      {
        id: "true",
        label: "Tačno - jednoglasna odluka odbora je dovoljna",
        isCorrect: false,
        explanation:
          "Jednoglasnost ne menja zabranu; glasanje lica koje nije u izvodu je razlog za poništavanje glasanja na biračkom mestu.",
        misconception: "BOARD_CAN_ADD_VOTER",
      },
    ],
    difficulty: "annulment",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["BOARD_CAN_ADD_VOTER"],
    authored: true,
  },
  {
    id: "A-I04-known",
    ruleId: "I04",
    type: "true_false",
    prompt: "Ako član odbora lično poznaje birača, provera javne isprave može da se preskoči.",
    choices: [
      {
        id: "false",
        label: "Netačno - isprava se traži i kada je birač poznat",
        isCorrect: true,
        explanation: "Lično poznavanje birača ne zamenjuje propisanu proveru identiteta.",
      },
      {
        id: "true",
        label: "Tačno - poznanstvo je dovoljno",
        isCorrect: false,
        explanation: "Izdavanje listića bez provere isprave je proceduralna nepravilnost.",
        misconception: "KNOWN_VOTER_NEEDS_NO_ID",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["KNOWN_VOTER_NEEDS_NO_ID"],
    authored: true,
  },
  {
    id: "A-P04-ballots",
    ruleId: "P04",
    type: "true_false",
    prompt: "Ako je primljeno manje listića nego što ima birača u izvodu, biračko mesto se ne otvara dok ne stigne dopuna.",
    choices: [
      {
        id: "false",
        label: "Netačno - mesto se otvara, a dopuna se traži u toku dana",
        isCorrect: true,
        explanation: "Zakon ovaj slučaj tretira drugačije od nedostatka izvoda, kutije ili kontrolnog lista.",
      },
      {
        id: "true",
        label: "Tačno - bez punog broja listića nema otvaranja",
        isCorrect: false,
        explanation: "Neotvaranje bi neosnovano uskratilo pravo glasa biračima koji su već u redu.",
        misconception: "FEWER_BALLOTS_BLOCKS_OPENING",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["FEWER_BALLOTS_BLOCKS_OPENING"],
    authored: true,
  },
  {
    id: "A-Z01-queue",
    ruleId: "Z01",
    type: "true_false",
    prompt: "U 20:00 vrata se zaključavaju i svi koji tada stoje u redu ispred biračkog mesta gube pravo da glasaju.",
    choices: [
      {
        id: "false",
        label: "Netačno - ko je u 20:00 u redu, mora dobiti priliku da glasa",
        isCorrect: true,
        explanation: "Svi koji se u 20:00 nalaze na biračkom mestu ili neposredno ispred njega moraju dobiti mogućnost da glasaju.",
      },
      {
        id: "true",
        label: "Tačno - posle 20:00 niko više ne glasa",
        isCorrect: false,
        explanation: "Odbijanje birača koji su na vreme stigli je teška povreda biračkog prava.",
        misconception: "QUEUE_CLOSES_AT_20",
      },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["QUEUE_CLOSES_AT_20"],
    authored: true,
  },
  {
    id: "A-N02-observer",
    ruleId: "N02",
    type: "true_false",
    prompt: "Akreditovani posmatrač ima pravo da prati otvaranje kutije i prebrojavanje glasova.",
    choices: [
      {
        id: "true",
        label: "Tačno - posmatrač prati rad odbora do predaje materijala",
        isCorrect: true,
        explanation:
          "Posmatrač prati izborne radnje od preuzimanja materijala, preko glasanja, do otvaranja kutije, brojanja i predaje materijala.",
      },
      {
        id: "false",
        label: "Netačno - brojanje je zatvoreno za posmatrače",
        isCorrect: false,
        explanation: "Sprečavanje posmatranja brojanja je ozbiljna nepravilnost i može biti prekršaj.",
        misconception: "OBSERVER_NOT_ALLOWED_AT_COUNT",
      },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["OBSERVER_NOT_ALLOWED_AT_COUNT"],
    authored: true,
  },
  {
    id: "A-T09-photo",
    ruleId: "T09",
    type: "classification",
    prompt:
      "Birač sam, bez ičijeg zahteva, fotografiše svoj popunjeni listić. Nema nikakvih naznaka da mu je nešto obećano. Kako to klasifikuješ?",
    choices: [
      {
        id: "irregular",
        label: "Nepravilnost - narušavanje reda, ali ne i dokaz kupovine glasa",
        isCorrect: true,
        explanation:
          "Neovlašćeno fotografisanje na biračkom mestu je narušavanje reda; sama fotografija ne dokazuje kupovinu glasa.",
      },
      {
        id: "criminal",
        label: "Moguće krivično delo kupovine glasova",
        isCorrect: false,
        explanation: "Za to bi bile potrebne dodatne činjenice o ponuđenoj koristi ili pritisku.",
        misconception: "EVERY_PHOTO_EQUALS_VOTE_BUYING",
      },
      {
        id: "allowed",
        label: "Dozvoljeno - svako sme da fotografiše svoj listić",
        isCorrect: false,
        explanation: "Tajnost glasanja je javni interes, a snimanje na biračkom mestu je ograničeno.",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["EVERY_PHOTO_EQUALS_VOTE_BUYING"],
    authored: true,
  },
  {
    id: "A-KG01-transport",
    ruleId: "KG01",
    type: "classification",
    prompt:
      "Stranka organizuje besplatan kombi prevoz do biračkog mesta. Nema dokaza o novcu, uslovljavanju niti traženju dokaza o glasanju. Kako to klasifikuješ?",
    choices: [
      {
        id: "check",
        label: "Proveri - sam prevoz nije dokaz, traže se dodatne činjenice",
        isCorrect: true,
        explanation:
          "Potrebno je da postoji stvarno nuđenje, obećanje ili davanje koristi u zamenu za određeno glasanje.",
      },
      {
        id: "criminal",
        label: "Moguće krivično delo davanja mita u vezi sa glasanjem",
        isCorrect: false,
        explanation: "Bez koristi uslovljene glasanjem, prevoz sam po sebi nije mito.",
        misconception: "PARTY_TRANSPORT_EQUALS_VOTE_BUYING",
      },
    ],
    difficulty: "criminal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["PARTY_TRANSPORT_EQUALS_VOTE_BUYING"],
    authored: true,
  },
  {
    id: "A-AN01-annul",
    ruleId: "AN01",
    type: "true_false",
    prompt: "Kada broj listića u kutiji premaši broj birača koji su glasali, birački odbor sam poništava glasanje na svom biračkom mestu.",
    choices: [
      {
        id: "false",
        label: "Netačno - odluku donosi nadležna izborna komisija po službenoj dužnosti",
        isCorrect: true,
        explanation:
          "Odbor utvrđuje i evidentira činjenice; poništavanje glasanja na biračkom mestu je odluka nadležne izborne komisije.",
      },
      {
        id: "true",
        label: "Tačno - odbor odmah proglašava glasanje poništenim",
        isCorrect: false,
        explanation: "Odbor nema ovlašćenje da sam poništi glasanje; on tačno unosi brojeve i obaveštava komisiju.",
        misconception: "BOARD_ANNULS_BY_ITSELF",
      },
    ],
    difficulty: "annulment",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["BOARD_ANNULS_BY_ITSELF"],
    authored: true,
  },
  {
    id: "A-ZP02-objection",
    ruleId: "ZP02",
    type: "true_false",
    prompt: "Primedba člana biračkog odbora u zapisniku je formalnost koja nema stvarni značaj za kasniji postupak.",
    choices: [
      {
        id: "false",
        label: "Netačno - primedba je često jedini pisani trag o spornom događaju",
        isCorrect: true,
        explanation:
          "Zapisnik izričito sadrži primedbe članova odbora; bez njih kasniji prigovor ostaje bez činjenične podloge.",
      },
      {
        id: "true",
        label: "Tačno - komisija ionako gleda samo brojeve",
        isCorrect: false,
        explanation: "Za zahtev za poništavanje traže se konkretne činjenice i dokazi, a primedba je upravo to.",
        misconception: "RECORD_OBJECTION_IS_OPTIONAL",
      },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["RECORD_OBJECTION_IS_OPTIONAL"],
    authored: true,
  },
  {
    id: "A-I07-deceased",
    ruleId: "I07",
    type: "classification",
    prompt:
      "U izvodu biračkog spiska nalazi se ime osobe koja je preminula pre dva meseca. Pored njenog imena nema potpisa. Kako to klasifikuješ?",
    choices: [
      {
        id: "info",
        label: "Informacija - sam upis nije dokaz da je neko glasao umesto nje",
        isCorrect: true,
        explanation:
          "Mnogo relevantnije pitanje je da li je evidentirano da je to lice glasalo; sam zapis u spisku nije dokaz zloupotrebe.",
      },
      {
        id: "criminal",
        label: "Moguće krivično delo - glas je sigurno zloupotrebljen",
        isCorrect: false,
        explanation: "Bez potpisa ili evidencije o glasanju nema osnova za takav zaključak.",
        misconception: "DECEASED_IN_REGISTER_EQUALS_FRAUD",
      },
    ],
    difficulty: "normal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["DECEASED_IN_REGISTER_EQUALS_FRAUD"],
    authored: true,
  },

  // ------------------------------------------------------------------ VIŠESTRUKI IZBOR
  {
    id: "A-P01-multi",
    ruleId: "P01",
    type: "multi_choice",
    prompt: "Koji nedostatak materijala sprečava otvaranje biračkog mesta? (izaberi sve tačne)",
    choices: [
      { id: "izvod", label: "Nedostaje izvod iz biračkog spiska", isCorrect: true, explanation: "Bez izvoda glasanje ne može da se sprovede." },
      { id: "kutija", label: "Nedostaje glasačka kutija", isCorrect: true, explanation: "Kutija je materijal bez kojeg se glasanje ne sprovodi." },
      { id: "kontrolni", label: "Nedostaje kontrolni list", isCorrect: true, explanation: "Kontrolni list je obavezan deo materijala pre otvaranja." },
      {
        id: "listici",
        label: "Primljeno je manje listića nego što ima upisanih birača",
        isCorrect: false,
        explanation: "Ovaj slučaj zakon izričito tretira drugačije: mesto se otvara, a listići se dopunjuju.",
        misconception: "FEWER_BALLOTS_BLOCKS_OPENING",
      },
      { id: "paravan", label: "Nedostaje jedan od paravana", isCorrect: false, explanation: "Nedostatak paravana se rešava organizacijom prostora, ne odlaganjem otvaranja." },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["FEWER_BALLOTS_BLOCKS_OPENING"],
    authored: true,
  },
  {
    id: "A-ZP01-multi",
    ruleId: "ZP01",
    type: "multi_choice",
    prompt: "Šta zapisnik biračkog odbora mora da sadrži pre nego što ga potpišeš? (izaberi sve tačne)",
    choices: [
      { id: "broj-birača", label: "Broj birača upisanih u izvod i broj onih koji su glasali", isCorrect: true, explanation: "Bez ovih brojeva kontrola računice nije moguća." },
      { id: "listici", label: "Broj listića u kutiji, važećih i nevažećih", isCorrect: true, explanation: "Ovi podaci ulaze u zakonom propisane provere." },
      { id: "kontrolni", label: "Podatak o kontrolnom listu", isCorrect: true, explanation: "Nalaz o kontrolnom listu se izričito unosi." },
      { id: "primedbe", label: "Primedbe članova biračkog odbora", isCorrect: true, explanation: "Zapisnik sadrži i primedbe članova odbora." },
      { id: "procena", label: "Procena kako će rezultat izgledati na nivou opštine", isCorrect: false, explanation: "Zapisnik utvrđuje činjenice sa tog biračkog mesta, ne procene." },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["RECORD_OBJECTION_IS_OPTIONAL"],
    authored: true,
  },
  {
    id: "A-V01-multi",
    ruleId: "V01",
    type: "multi_choice",
    prompt: "Šta mora biti ispunjeno kod glasanja van biračkog mesta? (izaberi sve tačne)",
    choices: [
      { id: "tri", label: "Kod birača idu tri člana biračkog odbora", isCorrect: true, explanation: "Propisan je sastav od tri člana." },
      { id: "predlagaci", label: "Članovi su imenovani na predlog različitih ovlašćenih predlagača", isCorrect: true, explanation: "Različiti predlagači su garancija nepristrasnosti." },
      { id: "potvrda", label: "Birač potpisuje potvrdu o pravu glasanja van biračkog mesta", isCorrect: true, explanation: "Bez potpisane potvrde listić se ne ubacuje u kutiju." },
      { id: "napuste", label: "Poverenici napuštaju prostoriju dok birač popunjava listić", isCorrect: true, explanation: "Tajnost važi i u stanu birača." },
      { id: "svedok", label: "Obavezno prisustvo policije", isCorrect: false, explanation: "Prisustvo policije nije uslov za glasanje van biračkog mesta." },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },

  // ------------------------------------------------------------------ NUMERIČKA PITANJA
  {
    id: "A-AN01-num",
    ruleId: "AN01",
    type: "numeric",
    prompt:
      "Prema potpisima je glasalo 642 birača, a u kutiji je pronađeno 650 listića. Koliko listića je više nego birača?",
    choices: [],
    numeric: { answer: 8, unit: "listića", hint: "650 − 642 = 8. Kada je taj broj veći od nule, reč je o zakonskom osnovu za poništavanje po službenoj dužnosti." },
    difficulty: "annulment",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["BOARD_ANNULS_BY_ITSELF"],
    authored: true,
  },
  {
    id: "A-AN02-num",
    ruleId: "AN02",
    type: "numeric",
    prompt:
      "Primljeno je 1000 listića, neupotrebljenih je 350, a u kutiji je 650. Koliko iznosi zbir neupotrebljenih i listića iz kutije?",
    choices: [],
    numeric: { answer: 1000, unit: "listića", hint: "350 + 650 = 1000. Ako bi taj zbir premašio broj primljenih, nastao bi zakonski osnov za poništavanje." },
    difficulty: "annulment",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },
  {
    id: "A-NR01-num",
    ruleId: "NR01",
    type: "numeric",
    prompt: "Zapisnik mora potpisati najmanje koliko članova biračkog odbora da bi rezultat uopšte mogao da se utvrdi?",
    choices: [],
    numeric: { answer: 3, unit: "člana", hint: "Ako zapisnik nije potpisalo najmanje tri člana odbora, rezultat sa tog biračkog mesta se ne može utvrditi." },
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },
  {
    id: "A-rokovi-num",
    ruleId: "I07",
    type: "numeric",
    prompt: "Koliko časova od zatvaranja biračkog mesta birač ima da podnese zahtev za poništavanje glasanja?",
    choices: [],
    numeric: { answer: 72, unit: "časa", hint: "Rok je 72 časa od zatvaranja biračkog mesta; o zahtevu odlučuje lokalna izborna komisija." },
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },

  // ------------------------------------------------------------------ SCENARIJA
  {
    id: "A-I05-scenario",
    ruleId: "I05",
    type: "scenario",
    prompt:
      "Birateljka ima ličnu kartu sa adresom iz ulice u kojoj je biračko mesto, ali je nema u izvodu. Šta je ispravno?",
    choices: [
      {
        id: "correct",
        label: "Ne izdati listić i uputiti je na lokalnu izbornu komisiju",
        isCorrect: true,
        explanation:
          "Omogućavanje glasanja licu koje nije upisano u izvod je jedan od zakonskih razloga za poništavanje glasanja na biračkom mestu.",
      },
      {
        id: "wrong-add",
        label: "Dopisati je u izvod jer je adresa očigledno tačna",
        isCorrect: false,
        explanation: "Odbor ne sme dopisivati birače u izvod.",
        misconception: "BOARD_CAN_ADD_VOTER",
      },
      {
        id: "wrong-issue",
        label: "Izdati listić uz napomenu u zapisniku",
        isCorrect: false,
        explanation: "Napomena ne otklanja posledicu: glasanje lica van izvoda ostaje osnov za poništavanje.",
        misconception: "BOARD_CAN_ADD_VOTER",
      },
    ],
    difficulty: "annulment",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["BOARD_CAN_ADD_VOTER"],
    authored: true,
  },
  {
    id: "A-T08-scenario",
    ruleId: "T08",
    type: "scenario",
    prompt:
      "Ispred biračkog mesta čovek traži od birača da mu pokažu fotografiju listića i nudi im novac. Koji je najispravniji redosled tvoje reakcije kao člana odbora?",
    choices: [
      {
        id: "correct",
        label: "Zabeleži vreme, opis i svedoke, obavesti predsednika odbora i prijavi policiji",
        isCorrect: true,
        explanation:
          "Nuđenje koristi u zamenu za dokaz o glasanju može predstavljati davanje mita u vezi sa glasanjem; bez evidencije nema osnova za postupanje.",
      },
      {
        id: "wrong-alone",
        label: "Izađi i sam ga oteraj, bez beleške",
        isCorrect: false,
        explanation: "Bez evidencije i prijave događaj ostaje bez ikakvih posledica.",
      },
      {
        id: "wrong-ignore",
        label: "Ne reaguj, jer se dešava izvan prostorije",
        isCorrect: false,
        explanation: "Radnja se tiče glasanja na tom biračkom mestu i mora biti evidentirana.",
      },
    ],
    difficulty: "criminal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },
  {
    id: "A-I02-scenario",
    ruleId: "I02",
    type: "scenario",
    prompt: "UV lampa pokazuje trag, a birač tvrdi da je član biračkog odbora na drugom mestu. Šta radiš?",
    choices: [
      {
        id: "correct",
        label: "Tražiš rešenje o imenovanju i tek uz dokaz nastavljaš proceduru",
        isCorrect: true,
        explanation: "Zakon predviđa izuzetak za člana biračkog odbora koji to dokaže odgovarajućim aktom.",
      },
      {
        id: "wrong-refuse",
        label: "Automatski odbijaš glasanje jer UV trag dokazuje da je već glasao",
        isCorrect: false,
        explanation: "Bez provere dokaza uskraćuješ pravo glasa osobi koja možda ispunjava izuzetak.",
      },
      {
        id: "wrong-allow",
        label: "Prihvataš objašnjenje na reč i izdaješ listić",
        isCorrect: false,
        explanation: "Bez dokaza ovo je omogućavanje ponovljenog glasanja.",
      },
    ],
    difficulty: "heavy",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    authored: true,
  },
  {
    id: "A-FR01-scenario",
    ruleId: "FR01",
    type: "scenario",
    prompt:
      "Posle brojanja, predsednik predlaže da se u zapisnik upiše broj koji „zaokružuje“ razliku od osam listića kako bi se računica složila. Šta je ispravno?",
    choices: [
      {
        id: "correct",
        label: "Odbiti izmenu, uneti stvarno prebrojane brojeve i primedbu u zapisnik",
        isCorrect: true,
        explanation:
          "Promena broja glasova ili listića radi „slaganja“ računice može predstavljati falsifikovanje rezultata glasanja.",
      },
      {
        id: "wrong-adjust",
        label: "Prihvatiti izmenu jer je razlika mala",
        isCorrect: false,
        explanation: "Veličina razlike ne menja prirodu radnje.",
      },
      {
        id: "wrong-silent",
        label: "Ne potpisati zapisnik, ali i ne unositi primedbu",
        isCorrect: false,
        explanation: "Bez primedbe ostaje samo tvoj nepotpis, bez objašnjenja zašto.",
        misconception: "RECORD_OBJECTION_IS_OPTIONAL",
      },
    ],
    difficulty: "criminal",
    publicationStatus: "published",
    reviewStatus: "legal_review",
    sourceIds: [],
    misconceptionTags: ["RECORD_OBJECTION_IS_OPTIONAL"],
    authored: true,
  },
];
